server:
  port: 9876
spring:
  application:
    name: auth-service
  # components:support:swagger
  main:
    allow-bean-definition-overriding: true
  # components:module:auth-store
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: immediate

eureka:
  instance:
    instance-id: auth-microservice-instance
    appname: auth-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


# components:support:token
support:
  jwt:
    secret-key: secretKey

# components:module:auth-store
filter:
  allow-list:
    - /auth/sha-test/**

# :components:client:member
client:
  member:
    url: http://localhost:8788/members